accent = "#7a9bb8"
cursor = "#c4622d"
foreground = "#f2ece6"
background = "#0a1420"
selection_foreground = "#f2ece6"
selection_background = "#3d5a75"
color0 = "#0a1420"
color1 = "#d97264"
color2 = "#8fb27e"
color3 = "#c4622d"
color4 = "#7a9bb8"
color5 = "#e8a882"
color6 = "#dce6f0"
color7 = "#f2ece6"
color8 = "#3d5a75"
color9 = "#d97264"
color10 = "#a4c294"
color11 = "#e8a882"
color12 = "#7a9bb8"
color13 = "#f7e8df"
color14 = "#dce6f0"
color15 = "#f2ece6"